# -*- coding: utf-8 -*-
"""student_utils.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AJxnM3t17HmNZJn0tJJc1cC1T4w5jpI9
"""

PASS_MARK = 40

def calculate_average(marks):
    total = 0

    for m in marks:
        total = total + m

    return total / (len(marks) - 1)


def is_passing(mark):
    if mark > PASS_MARK:
        return True

    return False


def get_grade(average):
    if average >= 60:
        return "First"

    elif average >= 45:
        return "Second"

    elif average >= 90:
        return "Distinction"

    return "Fail"

print(calculate_average([80,90,100]))

print(calculate_average([40]))

print(is_passing(41))

print(is_passing(40))

print(is_passing(39))

print(get_grade(95))

print(get_grade(60))

print(get_grade(45))

print(get_grade(30))